#符文标志 不懂不需要改
RuneLogo: '§0§0§0§0§f'
#解锁需要花费的金币
PayMoney: 2000
#符文页无属性时显示
NoAttribute: '&a- &f无'
#默认配置
Normal:
  #符文页名称
  disyname: '&a符文页 &b[ &f{page}&b ]'
  #默认解锁符文页数
  page: 1
  #默认使用的符文页
  use: 1
RanePage:
  #默认每个玩家能开多少符文页 不能超过27个
  Normal: 5
  authority:
    #拥有VIP1为子节点权限  权限名: "Rune.por.VIP1" 可解锁数量+10
    VIP1: 10
    VIP2: 15
# {Rune_Attributes} 变量的文本
Vau:
  #当变量为0的时候 是否不显示这段
  enable: true
  #Lore
  lore:
    hp1: '&b⊙ &a攻击伤害: &f+{b}'
    hp2: '&b⊙ &a防御护甲: &f+{b}%'
    hp3: '&b⊙ &a暴击几率: &f+{b}%'
    hp4: '&b⊙ &a暴击伤害: &f+{b}%'
    hp5: '&b⊙ &a吸血几率: &f+{b}%'
    hp6: '&b⊙ &a吸血效果: &fx{b}'
    hp7: '&b⊙ &a闪避几率: &f+{b}%'
    hp8: '&b⊙ &a命中几率: &f+{b}%'
    hp9: '&b⊙ &a破甲几率: &f+{b}%'
    hp10: '&b⊙ &a致盲几率: &f+{b}%'
    hp11: '&b⊙ &a凋零几率: &f+{b}%'
    hp12: '&b⊙ &a致命几率: &f+{b}%'
    hp13: '&b⊙ &a荆棘反弹: &f+{b}%'
#符文GUI
Gui:
  #上方物品ID
  ID1: '160:1'
  #下方物品ID
  ID2: '160:1'
  #已解锁物品的材质
  ID3: '340'
  #已解锁物品的材质 是否需要附魔
  ID3-Eff: true
  #未解锁的材质
  ID4: '339'
  #已解锁物品显示的Lore
  ID3Lore:
  - '&a&m&l------------------'
  - '&b符文页等级: &f{level}级'
  - '&b符文页属性: '
  - '{Rune_Attribute}'
  - '&a&m&l------------------'
  - ''
  - '&fShirt + 鼠标左键 &6使用此符文页'
  #未解锁物品显示的Lore
  ID4Lore:
  - '&a&m&l------------------'
  - ''
  - '&c该符文页未解锁'
  - '&a可&c左键&a花费 &f{money} &a金币来解锁符文页'
  - ''
  - '&a&m&l------------------'
#提示消息的前缀
Prefix: '&a[符文系统] '


#符文制作
RuneItem:
  #代号名
  Fw1:
    #符文名
    Name: '&b&l兽痕 &f&l[ 1级 ]'
    #符文ID
    Id: '351:6'
    #符文等级
    Level: 1
    #符文描述
    Lore:
    - '&7&l&m-------------------'
    - '&f + 0.3 &7伤害'
    - '&f + 6.0 &7伤害  &a&n雾'
    - '&f - 6.0 &7伤害  &a&n雾'
    - '&7&l&m-------------------'
    - ''
    - '&7&o我是你氪金也得不到的符文'
    #符文属性
    Attribute:
    - hp1:0.3






